-- Matchday Manager V4 Supabase setup
alter table public.players add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.matchdays add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.outstanding_payments add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.kitty_transactions add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.app_settings add column if not exists user_id uuid references auth.users(id) on delete cascade;
create table if not exists public.team_rules (id uuid primary key default gen_random_uuid(),created_at timestamptz default now(),user_id uuid references auth.users(id) on delete cascade default auth.uid(),rule_type text not null check (rule_type in ('lock','separate')),player_a uuid not null,player_b uuid not null);
alter table public.players alter column active set default true;alter table public.players alter column available set default false;alter table public.players alter column paid set default false;alter table public.players alter column rating set default 3;
alter table public.players enable row level security;alter table public.matchdays enable row level security;alter table public.outstanding_payments enable row level security;alter table public.kitty_transactions enable row level security;alter table public.app_settings enable row level security;alter table public.team_rules enable row level security;
create or replace function public.set_user_id() returns trigger language plpgsql security definer as $$ begin if new.user_id is null then new.user_id := auth.uid(); end if; return new; end; $$;
do $$ declare t text; begin foreach t in array array['players','matchdays','outstanding_payments','kitty_transactions','app_settings','team_rules'] loop execute format('drop trigger if exists set_%s_user_id on public.%I', t, t); execute format('create trigger set_%s_user_id before insert on public.%I for each row execute function public.set_user_id()', t, t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['players','matchdays','outstanding_payments','kitty_transactions','app_settings','team_rules'] loop execute format('drop policy if exists "%s_select_own" on public.%I',t,t); execute format('drop policy if exists "%s_insert_own" on public.%I',t,t); execute format('drop policy if exists "%s_update_own" on public.%I',t,t); execute format('drop policy if exists "%s_delete_own" on public.%I',t,t); execute format('create policy "%s_select_own" on public.%I for select using (auth.uid() = user_id)',t,t); execute format('create policy "%s_insert_own" on public.%I for insert with check (auth.uid() = user_id)',t,t); execute format('create policy "%s_update_own" on public.%I for update using (auth.uid() = user_id) with check (auth.uid() = user_id)',t,t); execute format('create policy "%s_delete_own" on public.%I for delete using (auth.uid() = user_id)',t,t); end loop; end $$;